//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class exemplo
    {
        [Display(Name = "id")]
        public int idexemplo { get; set; }
        [Display(Name = "TÍTULO")]
        [Required(ErrorMessage = "Este é um campo obrigatório")]
        public string Titulo { get; set; }
        public string caminhoImagem { get; set; }
        [Display(Name = "DESCRIÇÃO")]
        public string descricao { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
