//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imagem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class exemplo
    {
        [Display(Name = "ID")]
        public int idexemplo { get; set; }

        [Display(Name = "Título")]
        [Required(ErrorMessage = "Escreva um título !")]
        public string Titulo { get; set; }

        [Display(Name = "Descrição !")]
        public string descricao { get; set; }
        public string caminhoImagem { get; set; }
        public string status { get; set; }
        //essa linha é adicionada para podermos utilizar no controler
        //e fazer a cópia do arquivo para a pasta do projeto
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
